"""Autonomous, LLM-driven red-team engagement — URL in, report out.

This is the single end-to-end driver: you give it a target URL, the sovereign
Qwen model *plans* the engagement (recon -> scan -> correlate -> gated validate
-> report), the safety-gated tool layer *executes* it for real against the
in-scope target, active steps are auto-signed-off by the ROE approver, and the
full report bundle + Detect/Act handoff is written to disk.

    python run_agent.py                         # default: demo.testfire.net
    python run_agent.py https://demo.testfire.net
    python run_agent.py demo.testfire.net --no-validate

Only targets you are authorised to test may be used: the generated ROE is the
authorisation contract, and the scope guard fail-closes on anything else.
demo.testfire.net is IBM's public, intentionally-vulnerable AltoroMutual demo.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from urllib.parse import urlparse

from safeguard.engagement import Engagement
from safeguard.graph.checkpoint import SqliteCheckpointer
from safeguard.integration.act import ActIntegration
from safeguard.integration.detect import DetectIntegration
from safeguard.llm.client import LLMClient
from safeguard.llm.planner import LLMPlanner, RulePlanner
from safeguard.orchestrator import Orchestrator
from safeguard.reporting.report import Reporter
from safeguard.safety.approvals import ApprovalDecision

TOOLS = "tools.yaml"
SETTINGS = "settings.example.yaml"
RUNS_DIR = "runs-agent"
APPROVER = "operator"          # named ROE approver used to auto-sign-off validate


def load_dotenv() -> None:
    """Populate os.environ from the nearest .env (walking up from CWD).

    Values already present in the environment win, so an explicit export always
    overrides the file. Minimal parser: ``KEY=value`` / ``KEY="value"`` lines.
    """
    here = Path(__file__).resolve()
    for base in (here.parent, *here.parents):
        env_path = base / ".env"
        if not env_path.is_file():
            continue
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            os.environ.setdefault(key, val)
        return


def normalise_target(raw: str) -> str:
    """Return the bare hostname for scope/ROE (scanners add their own scheme)."""
    if "://" not in raw:
        raw = "//" + raw
    host = urlparse(raw).hostname or urlparse("//" + raw).hostname
    if not host:
        raise SystemExit(f"could not parse a hostname from {raw!r}")
    return host


def write_roe(host: str, out_dir: Path) -> Path:
    """Generate a single-domain, non-destructive black-box ROE for the target."""
    slug = host.replace(".", "-").replace(":", "-")
    engagement_id = f"eng-agent-{slug}"
    authorised_by = (os.environ.get("USER_EMAIL")
                     or os.environ.get("USER") or "operator").split("@")[0]
    roe = f"""# AUTO-GENERATED by run_agent.py — authorisation contract for this run.
engagement:
  id: "{engagement_id}"
  owner: "{APPROVER}"
  authorised_by: "{authorised_by}"
  authorisation_ref: "AUTO-{slug}"
  mode: "black_box"
  profile: "non_destructive"

scope:
  in_scope:
    domains:
      - "{host}"
    cidrs: []
    cloud_accounts: []
    repos: []
  exclusions:
    hosts: []
    paths: []

windows:
  timezone: "Asia/Kolkata"
  allowed:
    - days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
      start: "00:00"
      end: "23:59"

approvers:
  - "{APPROVER}"

budget:
  max_requests_per_second_per_target: 10
  max_concurrency_per_target: 4
  max_total_actions: 500
"""
    out_dir.mkdir(parents=True, exist_ok=True)
    roe_path = out_dir / "roe.generated.yaml"
    roe_path.write_text(roe, encoding="utf-8")
    return roe_path


def banner(title: str) -> None:
    print(f"\n{'=' * 68}\n{title}\n{'=' * 68}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Autonomous LLM red-team agent")
    ap.add_argument("target", nargs="?", default="demo.testfire.net",
                    help="target URL or hostname (default: demo.testfire.net)")
    ap.add_argument("--no-validate", action="store_true",
                    help="do not auto-approve active-validate steps (park instead)")
    ap.add_argument("--max-approvals", type=int, default=5,
                    help="safety cap on auto-approved active steps")
    args = ap.parse_args()

    load_dotenv()
    # Endpoint hygiene: this vLLM server serves the OpenAI API under /v1.
    base = os.environ.get("SAFEGUARD_LLM_BASE_URL", "").rstrip("/")
    if base and not base.endswith("/v1"):
        os.environ["SAFEGUARD_LLM_BASE_URL"] = base + "/v1"

    host = normalise_target(args.target)
    # Preserve an explicit port (e.g. :3000 for a local Juice Shop) for the
    # scan targets. The ROE scope stays keyed on the bare host; the scope guard
    # strips the :port from a target before matching, so http://host:port stays
    # in-scope. Recon (nmap) no-ops on the URL-form token and the scan node
    # falls back to state.targets, so the web scanners hit the right port.
    _p = urlparse(args.target if "://" in args.target else "//" + args.target)
    scan_target = f"http://{host}:{_p.port}" if _p.port else host
    web_ports = f"{_p.port},80,443" if _p.port else "80,443"
    eng_dir = Path(RUNS_DIR) / f"eng-agent-{host.replace('.', '-')}"
    roe_path = write_roe(host, eng_dir)

    banner(f"AUTONOMOUS RED-TEAM AGENT  →  {host}")
    print(f"ROE (authorisation): {roe_path}")

    eng = Engagement.build(
        roe_path=str(roe_path), tools_path=TOOLS, settings_path=SETTINGS,
        runs_dir=RUNS_DIR, dry_run=False,          # REAL execution
    )

    client = LLMClient.from_settings(eng.settings)
    if not client.configured:
        print("LLM base_url not configured (set SAFEGUARD_LLM_BASE_URL in .env)",
              file=sys.stderr)
        return 1
    print(f"planner: LLM  model={client.model}")
    print(f"         {client.base_url}")
    print(f"mode={eng.roe.mode.value}  profile={eng.roe.profile}  "
          f"scope={list(eng.roe.scope.domains)}")

    planner = LLMPlanner(client, eng.registry, fallback=RulePlanner(eng.registry))
    cp_path = eng_dir / "checkpoints.db"
    orch = Orchestrator.build(
        eng, planner=planner, checkpointer=SqliteCheckpointer(cp_path),
        recon_plan=["nmap"],                        # only ProjectDiscovery-clean bin here
        recon_params={"nmap": {"ports": web_ports}},  # web ports -> fast
        scan_plan=["nuclei", "nikto"],              # the actual web attack
    )

    init = orch.initial_state()
    if scan_target != host:
        init.targets = [scan_target]
        print(f"scan target: {scan_target}  (explicit port carried through)")

    banner("AGENT THINKING + ACTING (live)")
    result = orch.run(init)

    # Auto-sign-off any active-validate step the planner parked for approval.
    approvals = 0
    while (result.status == "interrupted" and not args.no_validate
           and approvals < args.max_approvals):
        pa = result.state.pending_approval or {}
        print(f"\n[APPROVAL] planner requests: {pa.get('tool')} on "
              f"{pa.get('target')} ({pa.get('technique')})")
        orch.approve(pa["request_id"], approver=APPROVER,
                     decision=ApprovalDecision.APPROVED)
        print(f"[APPROVAL] auto-signed by '{APPROVER}'; resuming…")
        approvals += 1
        result = orch.resume()

    if result.status == "interrupted":
        pa = result.state.pending_approval or {}
        print(f"\n[PARKED] active step awaiting approval: {pa.get('tool')} on "
              f"{pa.get('target')} (re-run without --no-validate to auto-approve)")

    st = result.state

    banner("AGENT REASONING TRACE (plan history)")
    for i, h in enumerate(st.plan_history, 1):
        tgt = f"  target={h['target']}" if h.get("target") else ""
        tool = f"  tool={h['tool']}" if h.get("tool") else ""
        print(f"{i:>2}. {h['action'].upper()}{tool}{tgt}\n    ↳ {h['rationale']}")

    banner("DISCOVERED ATTACK SURFACE")
    print(f"assets: {len(st.inventory)}")
    for a in st.inventory.assets():
        loc = f":{a.port}" if a.port else ""
        svc = f" {a.service or ''} {a.tech or ''}".rstrip()
        print(f"  - [{a.asset_type.value}] {a.address}{loc}{svc}")

    banner("FINDINGS")
    print(f"total: {len(st.ledger)}  severity={st.ledger.by_severity()}")
    for f in sorted(st.ledger.findings(),
                    key=lambda f: -(f.raw.get("risk") or {}).get("score", 0.0)):
        cves = f" {f.cve_ids}" if f.cve_ids else ""
        print(f"  - [{f.severity.value}] {f.title}  ({f.asset_ref}){cves}")

    if st.validations:
        banner("ACTIVE VALIDATIONS (gated, non-destructive)")
        for v in st.validations:
            print(f"  - {v.get('tool')} on {v.get('target')}: {v.get('result')} "
                  f"(approved by {v.get('approved_by')})")

    # Full report bundle + Detect/Act handoff.
    bundle = Reporter().build(st)
    paths = bundle.write(eng_dir / "report")
    outbox = eng_dir / "handoff"
    DetectIntegration().push(bundle.data, outbox)
    ActIntegration().push(bundle.data, outbox)

    banner("REPORT BUNDLE")
    for name in sorted(paths):
        print(f"  {paths[name]}")
    print(f"  handoff: {outbox}")

    rep = st.report or {}
    cov = rep.get("detection_coverage", {})
    banner("SUMMARY")
    print(f"status              : {result.status}")
    print(f"assets discovered   : {rep.get('assets', 0)}")
    print(f"findings            : {rep.get('findings', 0)}  "
          f"{rep.get('severity_counts', {})}")
    print(f"top risk score      : {rep.get('top_risk', 0)}")
    print(f"attack paths        : {len(rep.get('attack_paths', []))}")
    print(f"validations         : {len(st.validations)}")
    print(f"detection coverage  : {cov.get('coverage_pct', 0)}%  "
          f"gaps={len(cov.get('gaps', []))}")
    print(f"audit chain         : head={eng.audit.head[:16]}…  "
          f"events={len(eng.audit.events())}  intact={eng.audit.verify()}")
    print(f"\nRead: {paths.get('executive_summary.md')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
